# Generated by Django 4.1.3 on 2023-05-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'hs_birthday',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=360)),
                ('autor', models.CharField(max_length=360)),
                ('filename', models.CharField(max_length=360)),
                ('duration', models.DecimalField(decimal_places=6, max_digits=20)),
                ('cover', models.CharField(max_length=360)),
            ],
            options={
                'db_table': 'hs_books',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('front', models.CharField(max_length=150)),
                ('back_one', models.CharField(blank=True, max_length=150, null=True)),
                ('back_two', models.CharField(blank=True, max_length=150, null=True)),
                ('back_three', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField()),
                ('times', models.SmallIntegerField()),
                ('deck', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hs_cards',
            },
        ),
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deck', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'hs_decks',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('habit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hs_habits',
            },
        ),
        migrations.CreateModel(
            name='Karma',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('completed', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'hs_karma',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setting', models.CharField(max_length=255)),
                ('value', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'hs_settings',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=500)),
                ('date', models.DateField(null=True)),
                ('priority', models.SmallIntegerField(null=True)),
                ('ordering', models.SmallIntegerField(default=0)),
                ('project', models.CharField(max_length=64, null=True)),
                ('status', models.SmallIntegerField()),
                ('subtask', models.BigIntegerField()),
                ('repeat', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'hs_tasks',
            },
        ),
        migrations.CreateModel(
            name='HabitProgress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('completed', models.BigIntegerField(default=0)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.habit')),
            ],
            options={
                'db_table': 'hs_habits_progress',
            },
        ),
    ]
