# Generated by Django 4.1.3 on 2023-05-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=360)),
                ('autor', models.CharField(max_length=360)),
                ('filename', models.CharField(max_length=360)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
