# Generated by Django 4.1.3 on 2023-05-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('habit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hs_habits',
            },
        ),
        migrations.AlterModelTable(
            name='book',
            table='hs_books',
        ),
        migrations.CreateModel(
            name='HabitProgress',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.habit')),
            ],
            options={
                'db_table': 'hs_habits_progress',
            },
        ),
    ]
