# Generated by Django 4.1.3 on 2023-05-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_habit_alter_book_table_habitprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitprogress',
            name='completed',
            field=models.BigIntegerField(default=0),
        ),
    ]
