# Generated by Django 4.1.3 on 2023-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_settings_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
