# Generated by Django 4.1.3 on 2023-06-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_settings_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.SmallIntegerField(default=0),
        ),
    ]
