# Generated by Django 4.1.3 on 2023-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_book_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('year', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'hs_catalogue',
            },
        ),
    ]
