# Generated by Django 4.1.3 on 2023-05-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_habitprogress_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('karma', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'karma',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('ordering', models.SmallIntegerField(default=0)),
                ('project', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
