# Generated by Django 4.1.3 on 2023-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='url',
            field=models.CharField(max_length=350),
        ),
    ]
