# Generated by Django 4.1.3 on 2023-05-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_karma_task'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='karma',
            table='hs_karma',
        ),
        migrations.AlterModelTable(
            name='task',
            table='hs_tasks',
        ),
    ]
