# Generated by Django 4.1.3 on 2023-05-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_karma_table_alter_task_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karma',
            old_name='karma',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='karma',
            name='id',
        ),
        migrations.AlterField(
            model_name='karma',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
