# Generated by Django 4.1.3 on 2023-06-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_catalogue_author_alter_catalogue_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='code',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
