# Generated by Django 4.1.3 on 2023-06-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_catalogue_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
