# Generated by Django 4.1.3 on 2023-05-20 13:31

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_birthday_task_priority_task_status_alter_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='substask',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
