# Generated by Django 4.1.3 on 2023-05-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_task_substask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='substask',
            new_name='subtask',
        ),
    ]
