# Generated by Django 4.1.3 on 2023-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_substask_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='duration',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
