# Generated by Django 4.1.3 on 2023-05-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_book_duration_alter_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
