# Generated by Django 4.1.3 on 2023-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_task_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(default='48leis.jpg', max_length=360),
            preserve_default=False,
        ),
    ]
