# Generated by Django 4.1.3 on 2023-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setting', models.CharField(max_length=255)),
                ('value', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'hs_settings',
            },
        ),
    ]
