# Generated by Django 4.1.3 on 2023-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('front', models.CharField(max_length=10)),
                ('back_one', models.CharField(max_length=150)),
                ('back_two', models.CharField(max_length=150)),
                ('back_three', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('times', models.SmallIntegerField()),
                ('deck', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hs_cards',
            },
        ),
    ]
