# Generated by Django 4.1.3 on 2023-05-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='back_three',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='back_two',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
