# Generated by Django 4.1.3 on 2023-05-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_cards_back_three_alter_cards_back_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='back_one',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
