# Generated by Django 4.1.3 on 2023-05-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_cards_back_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='front',
            field=models.CharField(max_length=150),
        ),
    ]
